# Generated by Django 5.1.5 on 2025-05-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0002_pin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
