# Generated by Django 5.1.5 on 2025-05-14 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0003_pin_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='repin',
        ),
        migrations.AddField(
            model_name='pin',
            name='origin_pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repins', to='pin.pin'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pin.pin'),
        ),
        migrations.DeleteModel(
            name='Repin',
        ),
    ]
