# Generated by Django 4.2.9 on 2025-05-16 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0004_remove_comment_repin_pin_origin_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='origin_pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repins', to='pin.pin'),
        ),
    ]
