# Generated by Django 4.2.9 on 2025-05-17 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0005_alter_pin_origin_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='origin_pin',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repins', to='pin.pin'),
        ),
    ]
